name: Latest blogs updater
on:
  schedule:
    # Runs every day
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  update-chat-posts-within-readme:
    name: Update this repo's README with latest posts on blog.sylee.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.sylee.dev/feed.xml"
          max_post_count: 3
          comment_tag_name: BLOG-POST-LIST