name: Latest chat posts updater
on:
  schedule:
    # Runs every day
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  update-chat-posts-within-readme:
    name: Update this repo's README with latest posts on chat.sylee.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://chat.sylee.dev/feed"
          max_post_count: 5
          comment_tag_name: CHAT-POST-LIST